.changeset/silent-flies-drum.md, demo/src/pages/index.astro, demo/src/pages/markdown.md, demo/src/pages/youtube.astro, package-lock.json, packages/astro-embed-youtube/README.md, packages/astro-embed-youtube/YouTube.astro, packages/astro-embed-youtube/index.js, packages/astro-embed-youtube/package.json, packages/astro-embed/index.js, packages/astro-embed/package.json, tests/astro-embed-youtube.ts, tests/utils/render.ts
Adds a new `@astro-community/astro-embed-youtube` package to provide a YouTube embed component that uses https://github.com/paulirish/lite-youtube-embed to keep JS to a minimum.
=> Add a Youtube embed component

packages/astro-embed-twitter/package.json, packages/astro-embed-youtube/package.json, packages/astro-embed/package.json
Adds astro and astro-component keywords to packages containing .astro file exports. This should enable Astro to detect and add to vite.ssr.noExternal in astro.config.
=> Adds astro keywords to packages with .astro file exports

.changeset/slimy-cheetahs-kick.md, packages/astro-embed-twitter/Tweet.astro, tests/astro-embed-twitter.ts
This PR fix Tweet component crush when Twitter API return no entities somehow like in `https://twitter.com/addyosmani/status/1600553460180869120`
I don't know why this happens in this tweet.
I created a test that is coupled to this tweet specifically. Better to do it with Astro's tweeter user, but I don't know what caused this tweet to be without entities.
closes #27
=> Fix empty entities tweet

.changeset/forty-numbers-help.md, .changeset/small-squids-swim.md, demo/astro.config.mjs, demo/package.json, demo/src/env.d.ts, demo/src/pages/index.astro, demo/src/pages/integration.mdx, demo/src/pages/markdown.mdx, package-lock.json, package.json, packages/astro-embed-integration/README.md, packages/astro-embed-integration/index.js, packages/astro-embed-integration/package.json, packages/astro-embed-integration/remark-plugin.js, packages/astro-embed-twitter/package.json, packages/astro-embed-vimeo/package.json, packages/astro-embed-youtube/package.json, packages/astro-embed/README.md, packages/astro-embed/package.json
This PR drops support for Astro v1 and with it support for Astro-flavored Markdown, which allowed use of components in `.md` files.
The migration path is to move to `.mdx` files (with Astro’s MDX integration). This PR also rewrites the integration package to support MDX closing #34.
Also closes #43 — that bug was due to incompatibility with Astro v2. Astro v1 users should continue to use `astro-embed@0.2`, while Astro v2 users should use the next release, `astro-embed@0.3`.
=> Drop support for Astro v1 & AFMD, add support for MDX

.changeset/rare-geese-cover.md, .github/workflows/ci.yml, README.md, demo/src/pages/index.astro, demo/src/pages/markdown.mdx, demo/src/pages/twitter-with-js.astro, packages/astro-embed-twitter/README.md, packages/astro-embed-twitter/Tweet.astro, packages/astro-embed-twitter/Tweet.css, packages/astro-embed-twitter/matcher.js, packages/astro-embed/README.md, tests/astro-embed-twitter.ts
This PR overhauls the `<Tweet />` component to remove the requirement for authentication with Twitter’s API, which is basically impossible in any case now that their “hobbyist” tier for reading tweets costs $100/month 🙄 
| Before | After |
|---|---|
| <img width="504" alt="Example embeds with the old approach, showing more metadata and rendered media" src="https://github.com/delucis/astro-embed/assets/357379/86d8fbcd-8b93-412b-9adf-ff409705db69"> | <img width="517" alt="The same embeds after this PR, showing a more minimal design" src="https://github.com/delucis/astro-embed/assets/357379/8d729ee8-53ea-465f-a348-a072c7f825b3"> |
Key differences:
- The `<Tweet />` component must now receive a full URL to a tweet, not just an ID. Users will need to update these if you have any:
```diff
- …
```
=> More basic `<Tweet />` component without authentication

.changeset/hungry-candles-lie.md, .changeset/thick-eyes-decide.md, package-lock.json, packages/astro-embed-twitter/package.json, packages/astro-embed-vimeo/package.json
Removes the Twitter API SDK and `lite-vimeo-embed` deps which weren’t being used.
=> Remove unused package dependencies

packages/astro-embed/README.md
When I tried using this package, it wasn't working—my links remained as regular links. I use a few different integrations on my site and didn't think the order here mattered, but I found that the embeds integration only works when listed before the MDX integration.
This PR adds a callout to the README noting this requirement:
> [!IMPORTANT]
> The `embeds()` integration must be listed before the `mdx()` integration.
=> Add note about integration ordering

.changeset/spotty-baboons-kneel.md, packages/astro-embed-twitter/Tweet.astro
I forgot to delete an experimental `<script>` tag in the Tweet component in #46, which wasn’t actually doing anything. This PR removes that unused JS.
=> Remove pointless `<script>` in Tweet component

.changeset/little-fans-fold.md, packages/astro-embed-integration/remark-plugin.ts
Fixes #65
Previously, the remark plugin looked for the equivalent of `p > a:only-child` to find URLs to potentially replace with an embed and, when finding a URL match, replaced the link node. This resulted in DOM like `p > embed`.
#65 noticed this was causing issues if embed code included elements not permitted inside `<p>` (`<blockquote>` in the case of Twitter’s oEmbed markup). This causes HTML parsing to do some creative stuff and can cause some layout weirdness depending on what a user’s CSS looks like.
This PR updates the remark plugin to replace the full paragraph node with the embed instead of just the link, so this should no longer be an issue.
Existing embeds should render as expected without the wrapper `<p>` — although spacing between embeds may be impacted (`<p>` has default …
=> MDX integration embeds replace their parent paragraph instead of their link node

.changeset/flat-buses-tie.md, packages/astro-embed-integration/index.ts
Follow-up to #62 to actually error and provide some helpful logging if someone configures the embeds integration after the MDX integration.
=> Throw error if MDX & embeds integration are misconfigured

.changeset/tiny-kids-provide.md, package-lock.json, packages/astro-embed-youtube/YouTube.astro
Hi. I think is supposed to be upstream on lite-youtube, or even Starlight (maybe not as it was already discussed there) in not sure, but I'm opening this here and see where it goes.
This aims to solve #71
It basically overrides the CSS that is setting `height` to auto and `margin-top` to 1.5rem in Starlight `markdown.css`: [Line 4](https://github.com/withastro/starlight/blob/0c25c1f33bbfe311724784530c30ada44eb5de19/packages/starlight/style/markdown.css#L4) and 
[Line 43](https://github.com/withastro/starlight/blob/0c25c1f33bbfe311724784530c30ada44eb5de19/packages/starlight/style/markdown.css#L43).
For reference, after these changes:
Thank you.
=> fix: YouTube embed height in Starlight #71

.changeset/shiny-rivers-rule.md, packages/astro-embed-youtube/matcher.ts, tests/astro-embed-youtube.ts
YouTube Shorts shave a different URL format sometimes not accounted for in the current matcher regular expression. This PR updates that to correctly extract video IDs from `/shorts/` URLs.
=> Add support for `/shorts/` URLs in YouTube URL matcher

.changeset/old-crabs-argue.md, package-lock.json, packages/astro-embed-youtube/package.json
`lite-youtube-embed` [v0.3.0](https://github.com/paulirish/lite-youtube-embed/releases/tag/v0.3.0) and [v0.3.1](https://github.com/paulirish/lite-youtube-embed/releases/tag/v0.3.1) come with some nice improvements!
=> Upgrade lite-youtube-embed from 0.2.0 to 0.3.2

.changeset/happy-avocados-relate.md, .changeset/slow-icons-allow.md, packages/astro-embed-youtube/YouTube.astro, tests/astro-embed-twitter.mjs, tests/astro-embed-vimeo.mjs, tests/astro-embed-youtube.mjs, tests/utils/render.mjs, tsconfig.json
- Use progressive enhancement pattern for YouTube component to render the play button as a link until JavaScript loads.
- Use WebP poster images instead of JPEG for smaller file sizes.
=> YouTube component improvements

.changeset/hot-experts-reflect.md, docs/src/content/docs/components/youtube.mdx, packages/astro-embed-youtube/YouTube.astro, tests/astro-embed-youtube.mjs
Adds a `posterQuality` prop to the YouTube component for selecting higher or lower resolutions of the YouTube poster image.
=> Add `posterQuality` prop to `<YouTube>`

.changeset/spicy-phones-visit.md, docs/src/content/docs/components/youtube.mdx, packages/astro-embed-youtube/YouTube.astro, tests/astro-embed-youtube.mjs
- Uses `title` to set `data-title` at build time so it displays before the custom element is defined
- Documents that this attribute exists.
=> Improve `title` attribute support in `<YouTube>` and document it

.changeset/big-years-sing.md, .changeset/giant-coats-heal.md, .changeset/quick-news-double.md, docs/src/content/docs/components/vimeo.mdx, packages/astro-embed-vimeo/Vimeo.astro, packages/astro-embed-vimeo/Vimeo.css
- Tweaks play button style to better match Vimeo’s.
- Adds a `posterQuality` prop like the YouTube component has and sets a default of `480px` instead of `640px` to match YT.
- Uses a progressive enhancement pattern to display a link to the Vimeo video until the `<lite-vimeo>` JavaScript loads
=> Vimeo component improvements

.changeset/wet-chairs-cry.md, docs/src/content/docs/components/link-preview.mdx, packages/astro-embed-link-preview/LinkPreview.astro
Use https://css-tricks.com/line-clampin/#the-standardized-way to truncate the open graph description of LinkPreview at 3 lines instead of just the one.
=> Make number of `<LinkPreview>` description lines configurable

.changeset/large-dolls-burn.md, packages/astro-embed-integration/remark-plugin.ts
Closes #120 
Fixes an issue where the integration would match links that take up an entire paragraph even if they included a custom link.
For example, `[Check it out!](https://example.com)` would be converted to a `<LinkPreview>` component instead of rendering an `<a>` tag. This is now fixed and only plain URLs like `https://example.com` will match.
=> Only match URLs that don’t have a custom label

.changeset/beige-llamas-visit.md, packages/astro-embed-utils/index.ts
This pr closes #124
This pr changes the import from `linkedom` to `linkedom/worker` which enables it to work with other javascript runtimes as well.
=> fix build error when using with cloudflare adapter

.changeset/shaggy-experts-hammer.md, docs/src/content/docs/components/link-preview.mdx, package-lock.json, packages/astro-embed-link-preview/LinkPreview.astro
Fixes https://github.com/delucis/astro-embed/issues/129
Tried to be minimally invasive in my edits and add `showImage` and `showVideo` props which should function as if the OG url didn't have an image or video, essentially.
=> Add `hideMedia` prop to `LinkPreview`

.changeset/swift-horses-walk.md, package-lock.json, packages/astro-embed-youtube/package.json
Fixes #116 
Upgrades to https://github.com/paulirish/lite-youtube-embed/releases/tag/v0.3.3 in the `<YouTube>` component to fix accessibility issues with the play button.
=> Update `lite-youtube-embed` to v0.3.3

.changeset/cuddly-bears-smell.md, packages/astro-embed-vimeo/Vimeo.astro
Closes: https://github.com/delucis/astro-embed/issues/135
Fixes an issue with invalid Vimeo links throwing builds:
I tested this locally, I am not sure how to add a test for this since it is a private video link
=> Fix invalid Vimeo links

.changeset/twenty-shoes-stare.md, package-lock.json, packages/astro-embed-integration/package.json, packages/astro-embed-twitter/package.json, packages/astro-embed-vimeo/package.json, packages/astro-embed-youtube/package.json, packages/astro-embed/package.json
- Add `^5.0.0-beta` to `package.json` and `package-lock.json`.
Allows `astro-embed` to be installed in projects developed with **Astro v5**
=> Allows astro-embed to be installed in projects developed with Astro v5

.changeset/fifty-pigs-dream.md, demo/src/pages/index.astro, demo/src/pages/twitter-with-js-dark.astro, docs/src/content/docs/components/twitter.mdx, docs/src/content/docs/examples/tweet-with-js-dark.mdx, packages/astro-embed-twitter/Tweet.astro, packages/astro-embed-twitter/Tweet.css
This PR adds support of `theme` param, as you may want to use `dark` theme. Twitter allows to pick theme, see example here:
https://publish.twitter.com/?query=https%3A%2F%2Ftwitter.com%2Fastrodotbuild%2Fstatus%2F1511750228428435457&theme=dark&widget=Tweet
=> Add `theme` prop support to `Tweet` component

.changeset/proud-waves-jog.md, demo/src/pages/twitter.astro, packages/astro-embed-twitter/matcher.ts, tests/astro-embed-twitter.mjs
twitter changed their domain from `twitter.com` to `x.com` so the auto-embedder doesn't work for links with the new domain, I adjusted the regex to work with `x.com` too
=> update twitter url matching (x.com)

.changeset/eleven-ghosts-confess.md, packages/astro-embed-baseline-status/BaselineStatus.astro
I noticed that the browser icons start wrapping in an undesired way, because of the `max-width`.
So I removed the `max-width`.
=> fix wrapping of icons in `BaselineStatus`

.changeset/sixty-oranges-sneeze.md, packages/astro-embed-youtube/YouTube.astro, tests/astro-embed-youtube.mjs
ARIA commands must have an accessible name, read more: https://dequeuniversity.com/rules/axe/4.10/aria-command-name
Otherwise i'm getting this issue in lighthouse Accessibility report:
=> Fix accessible names for embed youtube link

.changeset/witty-ants-serve.md, demo/src/pages/bluesky.astro, package-lock.json, packages/astro-embed-bluesky/src/post.astro, packages/astro-embed-bluesky/src/styles.css
Of course, as soon as it's published I see there were style regressions. This fixes logo display and styling of links.
=> fix: correct logo display and link style

.changeset/shaggy-ties-laugh.md, package-lock.json, packages/astro-embed-bluesky/src/index.ts, packages/astro-embed-bluesky/src/post.astro
Allow an ATProto `PostView` to be passed to the BlueSky embed. It currently only accepts our extended interface, which isn't needed. Thanks @brob for spotting it
=> fix: allow PostView to be passed to embed

.changeset/clean-falcons-remain.md, packages/astro-embed-bluesky/src/utils.ts
I noticed hashtag links on Bluesky embeds were broken while playing around with the widget, just due to a minor typo in the URL composition.
- Correct typo `/hastag` → `/hashtag`
=> fix: Bluesky embed hashtag links broken

.changeset/tough-pigs-exercise.md, package-lock.json, packages/astro-embed-integration/package.json
Hi :wave:,
I noticed in a project that uses pnpm workspaces with hoisting disabled that `astro-embed-integration` is missing the dependency on `astro-embed-bluesky`. This PR adds it to the dependencies, so it can be resolved correctly.
I tried to follow the conventions, let me know if I should change anything.
=> fix: Add missing dependency of astro-embed-bluesky to integration
